name: Python Package Build for Linux

on:
  push:
    branches:
      - main
      - cayley
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  repository_dispatch:
    types: [pybind-wrapper]

jobs:
  build:
    name: Linux Wrapper Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["cp36-cp36m", "cp37-cp37m", "cp38-cp38", "cp39-cp39"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Linux wheels
      run: |
        sudo docker run --rm -e PLAT=manylinux_2_24_x86_64 -e PYTHON_VERSION=${{ matrix.python-version }} -v `pwd`:/io varunagrawal/gtdynamics-manylinux:latest -e GTDYNAMICS_PASSWORD /io/build-linux-wheels.sh
        # cleanup for custom runner
        sudo chown -R $(whoami):$(whoami) .
      env:
        GTDYNAMICS_PASSWORD: ${{ secrets.GTDYNAMICS_PASSWORD }}
    - name: Archive wheels
      uses: actions/upload-artifact@v2
      with:
        name: gtdynamics-1.0.0-${{ matrix.python-version }}-manylinux_2_24_x86_64.whl
        path: wheelhouse/gtdynamics-1.0.0-${{ matrix.python-version }}-manylinux_2_24_x86_64.whl
